### PR TITLE
Preserve key files already published to object store (closes #650)

### LINKED ISSUE #650: Wrong hash value for 2020-06-23 and 2020-06-24
## Current Implementation

Old keys are deleted and the remaining keys are repacked by day or by hour.
60 keys moved from 24.06.2020 to 23.06.2020.
44 keys are deleted from 23.06.2020
The hour files 2020-06-23-hour-08.zip, 2020-06-23-hour-13.zip, 2020-06-23-hour-17.zip are repacked to
2020-06-23-hour-10.zip, 2020-06-23-hour-15.zip, 2020-06-23-hour-18.zip
(Even the old hour files are superseded they are still on the server.)
## Suggested Enhancement

Leave the files as they are, do not remove old keys. 
## Expected Benefits

The files downloaded by the app have the same hash value as the file on the server.

### PR DESCRIPTION
**Pull request by EugenM-SAP**
## Checklist

* [x] Test your changes as thoroughly as possible before you commit them. Preferably, automate your test by unit/integration tests.
* [x] Make sure `mvn install` runs for the whole project and, if you touched any code in the respective service, submission and distribution service can be run with `spring-boot:run`

## Description

Solution consists of following changes:
  * Publish empty daily and hourly zip files to S3 even when minimum threshold of diagnosis keys is not met
  * Added rule to not overwrite key files already published to S3 (have an append-only distribution strategy)
  ** Note: index files are exception to this rule
  * Remove unit tests which are not valid with this new approach and adapt the rest to the new structure generation logic
  * Added new 'integration-test' Spring profile with its own "prod-like" yaml config
  * Added integration test to reproduce #650 scenario, which requires both H2 and the containerized S3 compatibile store when running locally
  * Added environment variable to control whether S3 key files get overwritten or not

### CODE REVIEW

File: services/distribution/src/test/java/app/coronawarn/server/services/distribution/assembly/diagnosiskeys/structure/directory/DiagnosisKeysDateDirectoryTest.java [hunk 1]
```diff
@@ -124,14 +126,17 @@ void testDoesNotIncludeCurrentDateInDirectoryStructure() {
...
-        "1970-01-05", List.of("0", "1", "2", "3", "4")), "1970-01-05");
+        "1970-01-03", listOfHoursAsStrings(0, 23),
+        "1970-01-04", listOfHoursAsStrings(0, 23),
+        "1970-01-05", listOfHoursAsStrings(0, 11)), "1970-01-05");
     assertThat(actualFiles).isEqualTo(expectedDateAndHourFiles);
   }
 
   @Test
-  void testDoesNotIncludeEmptyDatesInDirectoryStructure() {
+  @Disabled("Teporarily disabling this test as part of the fix for issue #650."
```
Comment (MichaelPFrey) [inline services/distribution/src/test/java/app/coronawarn/server/services/distribution/assembly/diagnosiskeys/structure/directory/DiagnosisKeysDateDirectoryTest.java:136]:
```suggestion
  @Disabled("Temporarily disabling this test as part of the fix for issue #650."
```

File: services/distribution/src/test/java/app/coronawarn/server/services/distribution/objectstore/integration/ObjectStoreFilePreservationIT.java [hunk 2]
```diff
@@ -0,0 +1,210 @@
...
+   * different files compared to the previous run, the result being: Day 2   -> submission of 80 keys   -> 1 empty file
+   * generated (different than what is currently on S3) Day 3   -> submission of 80 keys   -> 1 distributed containing
+   * 160 keys (different than 1 empty file on S3) Day 4   -> submission of 80 keys   -> 1 empty file (different than 1
+   * empty file on S3)
+   */
+  @Test
+  void files_once_published_to_objectstore_should_not_be_overriden_because_of_retention_or_shifting_policies()
+      throws IOException {
+
+    //keep data in the past for this test
```
Comment (michael-burwig) [inline services/distribution/src/test/java/app/coronawarn/server/services/distribution/objectstore/integration/ObjectStoreFilePreservationIT.java:119]: `// A leading whitespace makes this comment consistent with the rest of the code base`

File: services/distribution/src/main/java/app/coronawarn/server/services/distribution/assembly/diagnosiskeys/ProdDiagnosisKeyBundler.java [hunk 3]
```diff
@@ -83,6 +84,9 @@ protected void createDiagnosisKeyDistributionMap(Collection<DiagnosisKey> diagno
           if (diagnosisKeyAccumulator.size() >= minNumberOfKeysPerBundle) {
             this.distributableDiagnosisKeys.put(currentHour, new ArrayList<>(diagnosisKeyAccumulator));
             diagnosisKeyAccumulator.clear();
+          } else {
+            /* placeholder list is needed to be able to generate empty file - see issue #650 */
```
Comment (michael-burwig) [inline services/distribution/src/main/java/app/coronawarn/server/services/distribution/assembly/diagnosiskeys/ProdDiagnosisKeyBundler.java:88]: `//` for consistency

File: services/distribution/src/test/java/app/coronawarn/server/services/distribution/objectstore/integration/ObjectStoreFilePreservationIT.java [hunk 4]
```diff
@@ -0,0 +1,210 @@
...
+
+    //setup the 80 keys per day scenario
+    createDiagnosisKeyTestData(testStartDate, testEndDate, 80);
+
+    assembleAndDistribute(testOutputFolder.newFolder("output-before-retention"));
+    List<S3Object> filesBeforeRetention = getPublishedFiles();
+
+    triggerRetentionPolicy(testStartDate);
+
+    /* Trigger second distrubution after data retention policies were applied */
```
Comment (michael-burwig) [inline services/distribution/src/test/java/app/coronawarn/server/services/distribution/objectstore/integration/ObjectStoreFilePreservationIT.java:131]: Why alternate between commenting styles?

File: services/distribution/src/main/java/app/coronawarn/server/services/distribution/objectstore/publish/PublishedFileSet.java [hunk 5]
```diff
@@ -32,37 +33,52 @@
...
   /**
    * Creates a new PublishedFileSet for the given S3 objects with the help of the metadata provider.
    * The metadata provider helps to determine whether files have been changed, and are requiring
    * re-upload.
    *
    * @param s3Objects the list of s3 objects.
+   * @param distributionConiguration the system configuration wrt to distribution
    */
-  public PublishedFileSet(List<S3Object> s3Objects) {
+  public PublishedFileSet(List<S3Object> s3Objects, DistributionServiceConfig distributionConiguration) {
```
Comment (michael-burwig) [inline services/distribution/src/main/java/app/coronawarn/server/services/distribution/objectstore/publish/PublishedFileSet.java:47]: Probably better to pass `boolean forceUpdate` instead.

File: services/distribution/src/main/java/app/coronawarn/server/services/distribution/runner/S3Distribution.java [hunk 6]
```diff
@@ -56,7 +61,10 @@ public void run(ApplicationArguments args) {
 
       s3Publisher.publish(pathToDistribute);
       logger.info("Data pushed to Object Store successfully.");
-    } catch (UnsupportedOperationException | ObjectStoreOperationFailedException | IOException e) {
+    } catch (ObjectStoreOperationFailedException  e) {
+      logger.error("Communication with Object Store failed. Distribution run will be aborted", e);
+      Application.killApplication(applicationContext);
```
Comment (michael-burwig) [inline services/distribution/src/main/java/app/coronawarn/server/services/distribution/runner/S3Distribution.java:66]: What's the rationale behind distinguishing the 2 cases here?

File: services/distribution/src/test/java/app/coronawarn/server/services/distribution/assembly/diagnosiskeys/structure/directory/DiagnosisKeysDateDirectoryTest.java [hunk 7]
```diff
@@ -124,14 +126,17 @@ void testDoesNotIncludeCurrentDateInDirectoryStructure() {
...
-        "1970-01-05", List.of("0", "1", "2", "3", "4")), "1970-01-05");
+        "1970-01-03", listOfHoursAsStrings(0, 23),
+        "1970-01-04", listOfHoursAsStrings(0, 23),
+        "1970-01-05", listOfHoursAsStrings(0, 11)), "1970-01-05");
     assertThat(actualFiles).isEqualTo(expectedDateAndHourFiles);
   }
 
   @Test
-  void testDoesNotIncludeEmptyDatesInDirectoryStructure() {
+  @Disabled("Temporarily disabling this test as part of the fix for issue #650."
```
Comment (michael-burwig) [inline services/distribution/src/test/java/app/coronawarn/server/services/distribution/assembly/diagnosiskeys/structure/directory/DiagnosisKeysDateDirectoryTest.java:136]: `testWhenDemoProfileIsActiveItDoesIncludeCurrentDateInDirectoryStructure` sets a configuration parameter but does not reset it to it's original value afterwards.

Comment (michael-burwig) [reply services/distribution/src/test/java/app/coronawarn/server/services/distribution/assembly/diagnosiskeys/structure/directory/DiagnosisKeysDateDirectoryTest.java:136]: Mitigation would be use a mock or spy instead.

File: services/distribution/src/main/java/app/coronawarn/server/services/distribution/config/DistributionServiceConfig.java [hunk 8]
```diff
@@ -464,6 +464,7 @@ public SignatureInfo getSignatureInfo() {
     @Min(1)
     @Max(64)
     private Integer maxNumberOfS3Threads;
+    private Boolean forceUpdateKeyfiles = Boolean.FALSE;
```
Comment (michael-burwig) [inline services/distribution/src/main/java/app/coronawarn/server/services/distribution/config/DistributionServiceConfig.java:467]: consider setting this through the yaml file

File: services/distribution/src/main/java/app/coronawarn/server/services/distribution/runner/S3Distribution.java (hunk 6 above)
Comment (michael-burwig) [reply services/distribution/src/main/java/app/coronawarn/server/services/distribution/runner/S3Distribution.java:66]: suggestion: merge catches into 1

File: services/distribution/src/test/resources/application-integration-test.yaml [hunk 9]
```diff
@@ -0,0 +1,10 @@
+---
+logging:
+  level:
+    org:
+      springframework: debug
```
Comment (michael-burwig) [inline services/distribution/src/test/resources/application-integration-test.yaml:5]: consider removing or making it have an effect.

File: services/distribution/src/main/resources/application.yaml [hunk 10]
```diff
@@ -79,6 +79,8 @@ services:
       max-number-of-failed-operations: 5
       # The ThreadPoolTaskExecutor's maximum thread pool size.
       max-number-of-s3-threads: 4
+      # allows distribution to overwrite files which are published on the object store
```
Comment (stevesap) [inline services/distribution/src/main/resources/application.yaml:82]:
```suggestion
      # Allows distribution to overwrite files which are published to the object store.
```

File: services/distribution/src/test/java/app/coronawarn/server/services/distribution/assembly/diagnosiskeys/structure/directory/DiagnosisKeysDateDirectoryTest.java (hunk 7 above)
Comment (EugenM-SAP) [reply services/distribution/src/test/java/app/coronawarn/server/services/distribution/assembly/diagnosiskeys/structure/directory/DiagnosisKeysDateDirectoryTest.java:136]: Will go for the option to revert the state of the configuration back to what it was before the testWhenDemoProfileIsActiveItDoesIncludeCurrentDateInDirectoryStructure started. In the context of running tests in parallel this could be a problem, but more refactoring would be needed anyway to support such test runs.

File: services/distribution/src/main/java/app/coronawarn/server/services/distribution/objectstore/client/S3Object.java [hunk 11]
```diff
@@ -63,6 +63,15 @@ public String getCwaHash() {
     return cwaHash;
   }
 
+  /**
+   * Indicates if the S3 object is a file with diagnosis key content.
+   * The evaluation is based on the distribution logic which implies that such files are generated
+   * with a Date / Hour S3 key format (days: 1-31 / hours: 0-23) ending in 2 digits.
+   */
+  public boolean isDiagnosisKeyFile() {
```
[the remark this answers is not in the document]
Comment (EugenM-SAP) [reply services/distribution/src/main/java/app/coronawarn/server/services/distribution/objectstore/client/S3Object.java:71]: This is a good point. however, due to time constraints for meeting the next release, this will be treated as a technical debt and resolved separately. A refactoring is needed here to extract such key filename format evaluations in a dedicated class that can be performed on both S3Object as well as LocalFile.
