### PR TITLE
Fix/Validate exposure configuration at runtime

### LINKED ISSUE #122: Exposure configuration parameters not validated
The exposure configuration parameters are currently not validated after being read from the respective yml file. The validation code in ``ExposureConfigurationValidator`` is currently used in tests only.

However, the expected behavior shall be the following:
 - The ``RiskScoreParameters`` object is constructed based on yml file. (✅)
 - ``ExposureConfigurationValidator`` performs validation of the parameters.
 - In case of a failed validation, **do not** publish the exposure configuration parameters, **but do** generate and publish the diagnosis key bundles.
 - Clarify whether to keep any previously present (valid) configuration parameters on the object store if a validation error occurs.
 - Any validation errors shall be logged appropriately.

### PR DESCRIPTION
**Pull request by michael-burwig**
Fixes #122 

- Skips publishing the exposure configuration if its validation fails.
- Changes parameters directory name from ``parameters`` to``configuration``.
- Changes the name of the exposure configuration archive from ``index`` to ``exposure_configuration``
- Applies refactoring to ease the support of other configuration files. (see #78)

### CODE REVIEW

File: services/distribution/src/main/java/app/coronawarn/server/services/distribution/assembly/appconfig/structure/directory/AppConfigurationDirectory.java [hunk 1]
```diff
@@ -0,0 +1,96 @@
...
+    this.addWritable(new IndexingDecoratorOnDisk<>(countryDirectory));
+  }
+
+  private void addExposureConfigurationIfValid() {
+    try {
+      RiskScoreParameters exposureConfig = ExposureConfigurationProvider.readMasterFile();
+      AppConfigurationValidator validator = new ExposureConfigurationValidator(exposureConfig);
+      addArchiveIfMessageValid(EXPOSURE_CONFIGURATION_FILE_NAME, exposureConfig, validator);
+    } catch (UnableToLoadFileException e) {
+      logger.error("Exposure configuration will not be published! Unable to read configuration file from disk.");
```
Comment (christian-kirschnick) [inline services/distribution/src/main/java/app/coronawarn/server/services/distribution/assembly/appconfig/structure/directory/AppConfigurationDirectory.java:76]: Should add the exception to the log entry as well.
